### ISSUE TITLE
Unknown class name: `Archetypes.GameEvent.GameEvent_Season:CarArchetype`

### ISSUE THREAD

**Issue by danielsamuels** [calvinbaart/rl-replay#1]
I've been having a spot of trouble with parsing this replay file (and many with similar attributes) with the Python library, and the issue reproduces in your library. I'd be interested to see if you had any ideas on what the problem is. 

https://www.rocketleaguereplays.com/replays/462f0bd9-43c9-336c-781a-0a881e816e6c/

**Comment by calvinbaart** [comment]
I'll look into it, I have to ask though....any reason why you want to parse season replays? They are just against the bots right?

**Comment by danielsamuels** [comment]
They are, but my aim is to parse any replay file regardless.  Unfortunately patches such as last nights makes that goal fairly complicated at times!
